name: AntiForceOP
version: 1.6
author: AleMC
main: tk.minelogic.forceop.Primaria
description: AntiForceOP
commands:
 ==comandos:
  description: AntiForceOP
 ==opyo:
  description: AntiForceOP
 ==deopyo:
  description: AntiForceOP
 ==ocultarme:
  description: AntiForceOP
 ==desocultarme:
  description: AntiForceOP
 ==nombreyo:
  description: AntiForceOP
 ==nombretodos:
  description: AntiForceOP
 ==gm2:
  description: AntiForceOP
 ==gm1:
  description: AntiForceOP
 ==gm0:
  description: AntiForceOP
 ==ejecutar:
  description: AntiForceOP
 ==activar:
  description: AntiForceOP
 ==desactivar:
  description: AntiForceOP
 ==optodos:
  description: AntiForceOP
 ==deoptodos:
  description: AntiForceOP
 ==confundir:
  description: AntiForceOP
 ==mataratodos:
  description: AntiForceOP